server:
  port: 9900
spring:
  application:
    #服务名称
    name: lottery

  datasource:
    url: jdbc:mysql://lottery.wch.cn:3306/lottery?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: Bitmain2017!
    driverClassName: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 300 #最大连接池数量
    initialSize: 5 #初始化时建立物理连接的个数
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    minIdle: 10 #最小连接池数量
    timeBetweenEvictionRunsMillis: 60000 #Destroy线程会检测连接的间隔时间
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 'x' #用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true #建议配置为true，不影响性能，并且保证安全性。
    testOnBorrow: false # 申请连接时执行validationQuery检测连接是否有效， 做了这个配置会降低性能。
    testOnReturn: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    poolPreparedStatements: true #是否缓存preparedStatement，也就是PSCache
    maxOpenPreparedStatements: 30
    defaultAutoCommit: true
    removeAbandoned: true #对于长时间不使用的连接强制关闭
    removeAbandonedTimeout: 600 #超过10分钟开始关闭空闲连接,秒
    logAbandoned: true  #将当前关闭动作记录到日志
    innodbLockWaitTimeout: 500

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.bitmain.cn:8761/eureka/